definitions:
  services:
    docker:
      memory: 2048
  steps:
    - step: &eventserver-develop
        services:
          - docker
        name: run buid
        image: golang:1.14
        caches:
          - docker
          - node
        script:
          - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - docker-compose up -d
          - gofmt -d ./
          - go test -v -coverpkg=./... -coverprofile=coverage.log ./...
          - go tool cover -func coverage.log
        artifacts:
          - ./eventserver

pipelines:
  pull-requests:
    '**':
      - step: *eventserver-develop

  branches:
    develop:
      - step: *eventserver-develop