version: '3'

services:
  app:
    restart: always
    hostname: app
    container_name: event-server_app
    networks:
      - eventserver
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "user=root password=root dbname=testdb host=postgres connect_timeout=5 statement_timeout=30 port=5432 sslmode=disable"
      AUTH_USER: test
      AUTH_PASS: test

  postgres:
    image: postgres:14
    container_name: event-server_postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - eventserver
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb

  linter:
    image: golangci/golangci-lint
    networks:
      - eventserver
    volumes:
      - .:/code
    working_dir: /code

networks:
  eventserver:
