version: '3'

services:
  app:
    restart: always
    hostname: app
    container_name: event-server_app
    networks:
      - eventserver
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testdb
      DB_SSLMODE: disable
      AUTH_USER: test
      AUTH_PASS: test

  postgres:
    image: postgres:12
    container_name: event-server_postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - eventserver
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb

networks:
  eventserver:
