name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
    
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
    
    - name: Format code
      run: gofmt -d ./
    
    - name: Download code metrics library
      run: go get github.com/fzipp/gocyclo
      
    - name: Run code metrics
      run: gocyclo -avg . 
      
    - name: Test
      run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt ./...
      env:
        DATABASE_URL: user=root password=root dbname=testdb host=localhost port=5432 sslmode=disable
        AUTH_USER: test
        AUTH_PASS: test  
      
    - name: Code coverage
      run: go tool cover -func coverage.txt
