name: Release

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - name: 'Get next minor version'
        id: nexttag
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Commit and tag v${{ steps.nexttag.outputs.patch }}
        run: |
          git config --global user.name 'automatic release'
          git config --global user.email 'automatic.release@test.com'
          git commit -am "Bumping version to ${{ steps.nexttag.outputs.patch }}"
          git tag -a v${{ steps.nexttag.outputs.patch }} -m v${{ steps.nexttag.outputs.patch }}
          git push --follow-tags